const reasonCodes = [
  //cub prod//
  {
    code: '620',
    reason_id: 2,
    show_user: false,
    description: 'Delinquency Block',
    account_status_id: 8,
  },
  {
    code: '621',
    reason_id: 3,
    show_user: false,
    description: 'Risk Related Block',
    account_status_id: 8,
  },
  {
    code: '622',
    reason_id: 4,
    show_user: false,
    description: 'Compliance Block',
    account_status_id: 8,
  },
  {
    code: '624',
    reason_id: 6,
    show_user: false,
    description: 'OTP retries exceeded',
    account_status_id: 8,
  },
  {
    code: '625',
    reason_id: 7,
    show_user: false,
    description: 'Other',
    account_status_id: 8,
  },
  {
    code: '630',
    reason_id: 8,
    show_user: false,
    description: 'Account Closure by Cardholder - Fees',
    account_status_id: 9,
  },
  {
    code: '631',
    reason_id: 9,
    show_user: false,
    description: 'Account Closure by Cardholder - Customer Service',
    account_status_id: 9,
  },
  {
    code: '632',
    reason_id: 10,
    show_user: false,
    description: 'Account Closure by Cardholder - Product Features',
    account_status_id: 9,
  },
  {
    code: '633',
    reason_id: 11,
    show_user: false,
    description: 'Account Closure by Cardholder - No Use for Card',
    account_status_id: 9,
  },
  {
    code: '634',
    reason_id: 12,
    show_user: false,
    description: 'Account Closure by Cardholder - Other Reasons',
    account_status_id: 9,
  },
  {
    code: '635',
    reason_id: 13,
    show_user: false,
    description: 'Account Closure by Card Issuer',
    account_status_id: 9,
  },
  {
    code: '636',
    reason_id: 14,
    show_user: false,
    description: 'Other',
    account_status_id: 9,
  },
  {
    name: 'CANCELLED',
    id: 9,
    group: 'CANCELLED',
  },
  {
    name: 'DEFINITIVE_CANCELLATION',
    id: 40,
    group: 'DEFINITIVE_CANCELLATION',
  },
  //usfb prod//
  {
    code: '620',
    reason_id: 16,
    show_user: false,
    description: 'Delinquency Block',
    account_status_id: 35,
  },
  {
    code: '621',
    reason_id: 17,
    show_user: false,
    description: 'Risk Related Block',
    account_status_id: 35,
  },
  {
    code: '622',
    reason_id: 18,
    show_user: false,
    description: 'Compliance Block',
    account_status_id: 35,
  },
  {
    code: '624',
    reason_id: 20,
    show_user: false,
    description: 'OTP retries exceeded',
    account_status_id: 35,
  },
  {
    code: '625',
    reason_id: 21,
    show_user: false,
    description: 'Other',
    account_status_id: 35,
  },
  {
    code: '630',
    reason_id: 22,
    show_user: false,
    description: 'Account Closure by Cardholder - Fees',
    account_status_id: 36,
  },
  {
    code: '631',
    reason_id: 23,
    show_user: false,
    description: 'Account Closure by Cardholder - Customer Service',
    account_status_id: 36,
  },
  {
    code: '632',
    reason_id: 24,
    show_user: false,
    description: 'Account Closure by Cardholder - Product Features',
    account_status_id: 36,
  },
  {
    code: '633',
    reason_id: 25,
    show_user: false,
    description: 'Account Closure by Cardholder - No Use for Card',
    account_status_id: 36,
  },
  {
    code: '634',
    reason_id: 26,
    show_user: false,
    description: 'Account Closure by Cardholder - Other Reasons',
    account_status_id: 36,
  },
  {
    code: '635',
    reason_id: 27,
    show_user: false,
    description: 'Account Closure by Card Issuer',
    account_status_id: 36,
  },
  {
    code: '636',
    reason_id: 28,
    show_user: false,
    description: 'Other',
    account_status_id: 36,
  },
  {
    name: 'CANCELLED',
    id: 36,
    group: 'CANCELLED',
  },
  {
    name: 'DEFINITIVE_CANCELLATION',
    id: 41,
    group: 'DEFINITIVE_CANCELLATION',
  },
  //cub sandbox//

  {
    code: '620',
    reason_id: 1075,
    show_user: false,
    description: 'Delinquency Block',
    account_status_id: 635,
  },
  {
    code: '621',
    reason_id: 1076,
    show_user: false,
    description: 'Risk Related Block',
    account_status_id: 635,
  },
  {
    code: '622',
    reason_id: 1077,
    show_user: false,
    description: 'Compliance Block',
    account_status_id: 635,
  },
  {
    code: '624',
    reason_id: 1079,
    show_user: false,
    description: 'OTP retries exceeded',
    account_status_id: 635,
  },
  {
    code: '625',
    reason_id: 1080,
    show_user: false,
    description: 'Other',
    account_status_id: 635,
  },
  {
    name: 'CANCELLED',
    id: 636,
    group: 'CANCELLED',
  },
  {
    name: 'DEFINITIVE_CANCELLATION',
    id: 1932,
    group: 'DEFINITIVE_CANCELLATION',
  },
  {
    code: '630',
    reason_id: 1081,
    show_user: false,
    description: 'Account Closure by Cardholder - Fees',
    account_status_id: 636,
  },
  {
    code: '631',
    reason_id: 1082,
    show_user: false,
    description: 'Account Closure by Cardholder - Customer Service',
    account_status_id: 636,
  },
  {
    code: '632',
    reason_id: 1083,
    show_user: false,
    description: 'Account Closure by Cardholder - Product Features',
    account_status_id: 636,
  },
  {
    code: '633',
    reason_id: 1084,
    show_user: false,
    description: 'Account Closure by Cardholder - No Use for Card',
    account_status_id: 636,
  },
  {
    code: '634',
    reason_id: 1085,
    show_user: false,
    description: 'Account Closure by Cardholder - Other Reasons',
    account_status_id: 636,
  },
  {
    code: '635',
    reason_id: 1086,
    show_user: false,
    description: 'Account Closure by Card Issuer',
    account_status_id: 636,
  },
  {
    code: '636',
    reason_id: 1087,
    show_user: false,
    description: 'Other',
    account_status_id: 636,
  },

  //usfb sandbox//
  {
    name: 'CANCELLED',
    id: 1396,
    group: 'CANCELLED',
  },
  {
    name: 'DEFINITIVE_CANCELLATION',
    id: 1933,
    group: 'DEFINITIVE_CANCELLATION',
  },
];
